# docker compose up -d
# docker compose down ---- persist data in volumes
# docker compose down -v --- remove volumes

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    command: start-dev
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data

  openfga:
    image: openfga/openfga
    command: run
    ports:
      - '8081:8080'
    volumes:
      - openfga_data:/data

volumes:
  keycloak_data:
  openfga_data:
