// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // url: process.env["DATABASE_URL"],
    url: 'postgresql://postgres:4QY5F3guhcj0eObl@db.qjurctfaurpcojgeaday.supabase.co:5432/postgres',
  },
});
